version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/admin'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/client'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    target-branch: 'develop'
    directory: '/server'
    schedule:
      interval: 'weekly'
