name: Server CI

on:
  push:
    branches: ['develop']
    paths: ['manager/**']
  pull_request:
    branches: ['develop']
    paths: ['manager/**']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./manager/package-lock.json
      - run: npm ci --prefix manager
      - run: npm run build --if-present --prefix manager
